### ISSUE TITLE
Doublon de clé 'numeric' dans validation.php (laravel 10) 

### ISSUE THREAD

**Issue by thdaguin** [s-damian/laravel-lang-fr#4]
Bonjour,

Il y a un doublon de clés 'numeric' dans validation.php (laravel 10) ligne 100 et 102.
Pas grave mais ça sera plus joli avec 1 seule.

Bonne journée.

PS: merci pour cette traduction bien utile

**Comment by s-damian** [comment]
Bonjour,
Merci de me l'avoir signalé.
C'est corrigé.
